#!/usr/bin/env bash

cd $HOME/sof

rm -rf $HOME/.telegram-cli

install() {

rm -rf $HOME/.telegram-cli

sudo chmod +x tg

chmod +x sof

chmod +x SO

./SO

}

if [ "$1" = "ins" ]; then

install

fi

chmod +x install.sh

lua sof.lua

